config/routes.rb
Rails.application.routes.draw do
  
  root "quotes#index"    
  resources :quotes
  devise_for :users, :path => "/Mon_profil"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :user

    validates :content, presence: true, length: { minimum: 10, maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :quotes
  validates :email,
    presence: true,
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
    uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_quote, only: %i[ show edit update destroy ]


  def index
    @quotes = Quote.all
  end


  def show
    @quote = Quote.find(params[:id])
  end

  def new
    @quote = Quote.new
  end

 
  def edit
  end

 
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_quote
      @quote = Quote.find(params[:id])
    end

    def quote_params
      params.require(:quote).permit(:content).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <i class="fab fa-battle-net " style="font-size:35px"></i> <%= link_to "MyQuote App", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <% unless user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "New Quote", new_quote_path, class: "nav-link" %>
      </li>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestWcs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <div class="d-flex flex-column align-items-center">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>
<div class="d-flex">
    <%= render 'form', quote: @quote, class:"btn btn-info m-2" %>
</div>

<div class="d-flex">
    <%= link_to 'Show', @quote, class:"btn btn-primary m-2"  %> 
    
    <%= link_to 'Back', quotes_path, class:"btn btn-secondary m-2" %>
</div>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes list</h1>
    

<div class="container d-flex flex-wrap">
  <% @quotes.each do |quote| %>
    <div class="card col-sm-12 col-lg-2 m-3 p-2 d-flex align-items-center justify-content-center">
      <p class="h6 m-2"><em><%= quote.content %></em></p>
      <%= link_to 'Show', quote, class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

<br>

app/views/quotes/new.html.erb
<h1>New Quote</h1>
<div class="new-quote">
    <%= render 'form', quote: @quote %>

    <div class="d-flex justify-content-center">
        <%= link_to 'Back', quotes_path, class:"btn btn-secondary m-2" %>
    </div>
</div>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong class="display-3"></p><%= @quote.content %></strong>
  <p class="text-muted"><%= @quote.user.first_name %> <%= @quote.user.last_name %></p>
</p>
<div class="d-flex">
  <% if @quote.user == current_user %>
    <%= link_to 'Edit', edit_quote_path(@quote), class:"btn btn-info m-2"  %> 
    <%= link_to 'Destroy', @quote, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger m-2"  %> 
  <% end %>
  <%= link_to 'Back', quotes_path, class:"btn btn-secondary m-2" %>
</div>